// with-build/vue-app/src/examples/AlterState.vue
<template>
  <div>
      {{human.name}}, {{human.age}}, {{human.favouriteDinner}}. Counter: {{counter}}
  </div>
</template>

<script>
export default {
  data(){
    return{
      human: { name: 'Gaute', age: 28, favouriteDinner: 'Pizza'},
      counter: 0
    }
  },
  mounted(){
    this.human.favouriteDinner = 'Candy';
    this.counter++;
  }
}
</script>

// with-build/react-app/src/examples/AlterState.js
import React, { useEffect } from 'react';

function AlterState() {
    const [human, setHuman] = React.useState({ name: 'Gaute', age: 28, favouriteDinner: 'Pizza' });
    const [counter, setCounter] = React.useState(0);

    useEffect(() => {
        setHuman({ ...human, favouriteDinner: 'Candy' });
        setCounter(counter + 1);
    }, []);

    return (
        <div>
            {human.name}, {human.age}, {human.favouriteDinner}. Counter: {counter}
        </div>
    );
}

export default AlterState;
