// react/src/components/AddTodo.tsx
import { useState } from 'react'
import { useStore } from '../AppStoreProvider'
import styles from './AddTodo.module.css'

export function AddTodo(){
  const [input, setInput] = useState('')
  const context = useStore()

  function addTodo() {
    if(input){
      context.addTodo(input)
      setInput('')
    }
  }

  return (
    <section className={styles.addRow}>
      <label className={styles.label}>
        What to do?
        <input 
          type="text" 
          value={input}
          onInput={(event: React.FormEvent<HTMLInputElement>) => setInput(event.currentTarget.value)}
          onKeyUp={event => event.code === 'Enter' && addTodo()}
        />
      </label>
      <button onClick={addTodo} disabled={!input} className={styles.addButton}>Add</button>
    </section>
  )
}

// angular/src/app/add-todo/add-todo.component.ts
import { Component } from '@angular/core';
import { StoreService } from '../store.service'

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.css']
})
export class AddTodoComponent {

  input = ''

  constructor(private storeService: StoreService) {}

  addTodo(){
    if(this.input){
      this.storeService.todos.next([...this.storeService.todos.value, this.input])
      this.input = ''
    }
  }
}

<section>
  <label>
    What to do?
    <input type="text" [(ngModel)]="input" (keyup.enter)="addTodo()" />
  </label>
  <button [disabled]="!input" (click)="addTodo()">Add</button>
</section>
