// vue/src/components/AddTodo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { store } from '../store'

const input = ref('')
function addTodo(){
  store.todos.push(input.value)
  input.value = ''
}
</script>

<template>
  <section>
    <label>
      What to do?
      <input type="text" v-model="input" @keyup.enter="addTodo"/>
    </label>
    <button :disabled="!input" @click="addTodo">Add</button>
  </section>
</template>

<style scoped>
section{
  display: flex;
  gap: 5px;
  align-items: flex-end;
}

label{
  flex: 1;
  display: flex;
  flex-direction: column;
}

input, button{
  font-size: 1.5rem;
  font-family: inherit;
  height: 40px;
  box-sizing: border-box;
}
</style>

// angular/src/app/add-todo/add-todo.component.ts
import { Component } from '@angular/core';
import { StoreService } from '../store.service'

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.css']
})
export class AddTodoComponent {

  input = ''

  constructor(private storeService: StoreService) {}

  addTodo(){
    if(this.input){
      this.storeService.todos.next([...this.storeService.todos.value, this.input])
      this.input = ''
    }
  }
}

<section>
  <label>
    What to do?
    <input type="text" [(ngModel)]="input" (keyup.enter)="addTodo()" />
  </label>
  <button [disabled]="!input" (click)="addTodo()">Add</button>
</section>
