// with-build/vue-app/src/App.vue
<template>
  <div>
    <InputBind/>
    <ConditionallyShow/>
    <List/>
    <CssClass/>
    <AlterState/>
  </div>
</template>

<script>

export default {
  components:{
    InputBind: () => import('@/examples/InputBind'),
    ConditionallyShow: () => import('@/examples/ConditionallyShow'),
    List: () => import('@/examples/List'),
    CssClass: () => import('@/examples/CssClass'),
    AlterState: () => import('@/examples/AlterState'),
  }
}
</script>

// with-build/react-app/src/App.js
import React from 'react';
import InputBind from './examples/InputBind';
import ConditionallyRender from './examples/ConditionallyRender';
import List from './examples/List';
import CssClass from './examples/CssClass';
import AlterState from './examples/AlterState';

function App() {
  return (
    <>
      <InputBind/>
      <ConditionallyRender/>
      <List/>
      <CssClass/>
      <AlterState/>
    </>
  );
}

export default App;
